version: "3.8"

services:
  foodhub:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: foodhub
    restart: unless-stopped
    ports:
      - "2005:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
